import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Navbar} from "@/components/Navbar";
import {Sidebar} from "@/components/Sidebar";
import {
  Mulish,
} from "next/font/google";
import Footer from "@/components/Footer";
import BottomBar from "@/components/BottomBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


// Initialize the font with the subsets and weights you want to use
 const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mulish.variable} antialiased`}
      >
        <div className=" flex flex-col h-screen overflow-hidden font-mulish">
          <Navbar />
          <main className="flex h-[calc(100%-135px)] sm:h-[calc(100%-65px)]">
            <Sidebar/>
            <div className="flex-1 relative overflow-auto h-full">
              {children}
            </div>
          </main>
          <Footer/>
          <BottomBar/>
        </div>
      </body>
    </html>
  );
}
